# DMP Logging Configuration
# High-Performance Real-time Risk Control System

[global]
level = "info"
pattern = "[%Y-%m-%d %H:%M:%S.%f] [%l] [%s:%#] [%!] %v"
flush_interval_ms = 100

[console]
enabled = true
level = "info"
pattern = "[%Y-%m-%d %H:%M:%S.%f] [%l] [%s:%#] [%!] %v"

[file]
enabled = true
level = "info"
filename = "logs/dmp.log"
max_size_mb = 100
max_files = 10
rotation_hour = 0
rotation_minute = 0

[async]
queue_size = 8192
threads = 2
flush_interval_ms = 100
