# DMP Server Configuration
# High-Performance Real-time Risk Control System

[server]
host = "0.0.0.0"
port = 8080
threads = 4
max_connections = 1000
timeout_seconds = 30

[logging]
level = "info"
file = "logs/dmp.log"
max_size_mb = 100
max_files = 10
pattern = "[%Y-%m-%d %H:%M:%S.%f] [%l] [%s:%#] [%!] %v"

[performance]
target_p99_ms = 50
target_qps = 10000
enable_profiling = true
memory_pool_size_mb = 512

[security]
enable_ssl = false
cert_file = ""
key_file = ""
require_auth = false

[monitoring]
enable_metrics = true
metrics_port = 9090
enable_health_check = true
health_check_interval_seconds = 30
